[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  command = "npm start"
  port = 8888
  targetPort = 3000
  publish = "public"
  framework = "create-react-app"

[build.environment]
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]